# Generated by Django 5.0.4 on 2024-04-25 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('key_tag', models.CharField(max_length=255)),
                ('validity_duration_days', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='inactive', max_length=10)),
                ('procurement_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Access Key',
                'verbose_name_plural': 'Access Keys',
            },
        ),
    ]
