# Generated by Django 5.0.4 on 2024-04-25 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='validity_duration_days',
            field=models.IntegerField(default=30, help_text='Validity duration in days', validators=[django.core.validators.MaxValueValidator(365)], verbose_name='Validity in days'),
        ),
    ]
