# Generated by Django 5.0.4 on 2024-04-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0003_alter_accesskey_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesskey',
            old_name='expires_at',
            new_name='expiry_date',
        ),
    ]
