# Generated by Django 5.0.4 on 2024-05-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0003_alter_accesskey_validity_duration_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesskey',
            options={'ordering': ['-created_at'], 'verbose_name': 'Access Key', 'verbose_name_plural': 'Access Keys'},
        ),
        migrations.AlterUniqueTogether(
            name='accesskey',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='key_tag',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
