# Generated by Django 5.0.4 on 2024-04-23 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0004_rename_expires_at_accesskey_expiry_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='key_tag',
            field=models.CharField(default='sample', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='accesskey',
            unique_together={('owner', 'key_tag')},
        ),
    ]
