# Generated by Django 5.0.4 on 2024-04-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='inactive', max_length=10),
        ),
    ]
